all: sserver
sserver: server.o tcpstream.o tcpacceptor.o
	g++ server.o tcpstream.o tcpacceptor.o -o sserver

server.o: server.cc
	g++ -c server.cc

tcpstream.o: tcpstream.cc
	g++ -c tcpstream.cc

tcpacceptor.o: tcpacceptor.cc
	g++ -c tcpacceptor.cc

clean:
	rm -rf *o sserver

