all: cclient


cclient: client.o tcpstream.o tcpconnector.o
	g++ client.o tcpstream.o tcpconnector.o -o cclient

client.o: client.cc
	g++ -c client.cc

tcpstream.o: tcpstream.cc
	g++ -c tcpstream.cc

tcpconnector.o: tcpconnector.cc
	g++ -c tcpconnector.cc

clean:
	rm -rf *o cclient

